// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36d1hiDWKB2StKHRiWisNgWXLoY8XZqM',
    appId: '1:1054012620906:android:76ef5b31ce6251fb0b4a13',
    messagingSenderId: '1054012620906',
    projectId: 'we-chat-3b72c',
    storageBucket: 'we-chat-3b72c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIh22_6WxLG5KiWpmOy33H_4WTb85N7AA',
    appId: '1:1054012620906:ios:3144fe4a07c6e3450b4a13',
    messagingSenderId: '1054012620906',
    projectId: 'we-chat-3b72c',
    storageBucket: 'we-chat-3b72c.appspot.com',
    androidClientId: '1054012620906-mpb4ja99m56f1cirv92ev74ob3h03rlh.apps.googleusercontent.com',
    iosClientId: '1054012620906-idie6qtfmt6i210aeg6kaof5q2oo6db6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
